### ISSUE TITLE
Checker Error

### ISSUE THREAD

**Issue by BLLManitoba** [aclew/AAS-minCHAT-Checker#10]
When loading the .txt file version of the elan file, the app won't process the file and gives this message:

> Error: An error has occurred. Check your logs or contact the app author for clarification.

I've attached a sampling of the files that are giving this error right now.
[1499.txt](https://github.com/aclew/AAS-minCHAT-Checker/files/4032744/1499.txt)
[rely_3528.txt](https://github.com/aclew/AAS-minCHAT-Checker/files/4032751/rely_3528.txt)
[rely_9398.txt](https://github.com/aclew/AAS-minCHAT-Checker/files/4032757/rely_9398.txt)
[1156.txt](https://github.com/aclew/AAS-minCHAT-Checker/files/4032762/1156.txt)
[1735.txt](https://github.com/aclew/AAS-minCHAT-Checker/files/4032763/1735.txt)

**Comment by marisacasillas** [comment]
thanks! the issues were:
- incorrectly formatted timestamps (1156, 1735)
- inconsistent tier-speaker names (1499)
- a bug that doesn't handle files with no non-CHI speech (now fixed!)
