### ISSUE TITLE
Error screen

### ISSUE THREAD

**Issue by Aahnix** [aclew/AAS-minCHAT-Checker#14]
file number 5613 results in an error

"Error: An error has occurred. Check your logs or contact the app author for clarification."

attached is a screenshot of the error page:
![image](https://user-images.githubusercontent.com/54598012/88849831-75470e00-d1b8-11ea-91c8-6b60e41d986c.png)

**Comment by marisacasillas** [comment]
The file had some speaker label mismatches between tiers:
- the speaker for xds@FC1 listed as 'MC1'
- the speaker for xds@UC1 listed as 'UC2'

Multiple people have made this error in the past; it is easy to make this error when adding new tiers, and it's not obvious during manual file checks. I'm opening a new issue to handle these kinds of errors a little more smoothly—the current error message is not very helpful :) Thanks!
