### ISSUE TITLE
on_off tier

### ISSUE THREAD

**Issue by ebergelson** [aclew/AAS-minCHAT-Checker#6]
i can't find documentation of it, but isn't on_off a tier we're supposed to have? it's identical to code_num except it contains the onset and offset timestamp in milliseconds, whereas code_num is the # of the clip.  if i've got this right, we should:

-   add it to instructions in #6 on readme.
-  fix the alert 'wrong format tier(s) name: on_off'

**Comment by marisacasillas** [comment]
fixed; commit overlap with #7. thanks!
